stage('child') {
    node {
        sh """
            echo "hello from child"
            pwd
        """
        pluginCommand()
    }
}

stage('child Deploy') {
    node {
        sh """
            echo "depoyed"
        """
    }
}

