#!/bin/sh

set -e

PROJECT_FOLDER=$(readlink -f "$(dirname "$0")")


java -cp $PROJECT_FOLDER/target/dependency/commons-cli-1.3.1.jar:$PROJECT_FOLDER/target/dependency/groovy-all-2.4.15.jar:$PROJECT_FOLDER/target/dependency/commons-io-2.6.jar:$PROJECT_FOLDER/target/dependency/snakeyaml-1.17.jar org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain -Dscript.name=jenny.groovy $PROJECT_FOLDER/jenny.groovy $@

