#!/bin/sh

set -e

PROJECT_FOLDER="$(dirname "$(readlink -f "$0")")"

if [ ! -d "$PROJECT_FOLDER/target/dependency" ]; then
    CURRENT_FOLDER=$(pwd)
    cd "$PROJECT_FOLDER"
    mvn dependency:copy-dependencies > /tmp/jenny_download_dependencies.txt 2>&1
    cd "$CURRENT_FOLDER"
fi # [ ! -d target/dependency ]

#echo java -cp $PROJECT_FOLDER/target/dependency/commons-cli-1.3.1.jar:$PROJECT_FOLDER/target/dependency/groovy-all-2.4.15.jar:$PROJECT_FOLDER/target/dependency/commons-io-2.6.jar:$PROJECT_FOLDER/target/dependency/snakeyaml-1.17.jar org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain -Dscript.name=$PROJECT_FOLDER/jenny.groovy $PROJECT_FOLDER/jenny.groovy $@

java -cp $PROJECT_FOLDER/target/dependency/commons-cli-1.3.1.jar:$PROJECT_FOLDER/target/dependency/groovy-all-2.4.15.jar:$PROJECT_FOLDER/target/dependency/commons-io-2.6.jar:$PROJECT_FOLDER/target/dependency/snakeyaml-1.17.jar org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain -Dscript.name=$PROJECT_FOLDER/jenny.groovy $PROJECT_FOLDER/jenny.groovy $@

