stage('Simple dir test') {
    node {
        sh """
            pwd
        """
        echo pwd()

        dir('/tmp/') {
            sh """
                pwd
            """
            echo pwd()
        }

        sh """
            pwd
        """
        echo pwd()
    }
}

