properties([
    parameters([
        string(name: 'string_parameter', defaultValue: 'parent',
                description: 'A parent value string parameter')
    ])
])

stage('Parent') {
    node {
        sh """
            echo hello from parent
            pwd
        """
        pluginCommand()
        pluginCommand1p("param1")
        pluginCommand2p("param1", "param2")
    }

    build job: "child",
          parameters: [
            [$class: 'StringParameterValue', name: 'string_parameter', value: string_parameter]
          ]

    build job: "child-2-aliased",
          parameters: [
            [$class: 'StringParameterValue', name: 'string_parameter', value: string_parameter]
          ]
}

