stage('test junit') {
    node {
        deleteDir()
        checkout scm

        docker.image('jenny_test_junit').inside {
            deleteDir()
            checkout scm

            junit "reports/*.xml"
        }
    }
}
