stage('test archiveArtifacts') {
    node {
        deleteDir()
        checkout scm

        archiveArtifacts artifacts: 'files/**'
    }

    node {
        docker.image('maven:3.5.3').inside {
            deleteDir()
            checkout scm

            archiveArtifacts artifacts: 'file.txt'
        }
    }
}

stage('check files') {
    node {
        sh """
            ls /tmp/jenny-target | sort
            cat /tmp/jenny-target/file.txt
            cat /tmp/jenny-target/files/file1.txt
            cat /tmp/jenny-target/files/file2.txt
            cat /tmp/jenny-target/files/nested/nested.txt
        """
    }
}

stage('test unarchive') {
    node {
        deleteDir()

        unarchive mapping: [
            "files/": ".",
            "file.txt": "renamed-file.txt"
        ]

        sh """
            ls | sort
            cat renamed-file.txt
            cat files/file1.txt
            cat files/file2.txt
            cat files/nested/nested.txt
        """
    }
}

