stage('test archiveArtifacts') {
    node {
        deleteDir()
        checkout scm

        archiveArtifacts artifacts: 'file1.txt'
    }

    node {
        docker.image('maven:3.5.3').inside {
            deleteDir()
            checkout scm

            archiveArtifacts artifacts: 'file2.txt'
        }
    }
}

stage('check files') {
    node {
        sh """
            ls /tmp/jenny-target
            cat /tmp/jenny-target/file1.txt
            cat /tmp/jenny-target/file2.txt
        """
    }
}
