stage('unarchive Test') {
    node {
        // -------------------------------------------------------------------
        // Generate artifact
        // -------------------------------------------------------------------
        sh """
            mkdir -p artifacts
            echo "artifact1" > artifacts/artifact1
            echo "artifact2" > artifacts/artifact2
        """

        // -------------------------------------------------------------------
        // archive it
        // -------------------------------------------------------------------
        archiveArtifacts artifacts: 'artifacts/artifact1', fingerprint: true
        archiveArtifacts artifacts: 'artifacts/artifact2', fingerprint: true

        // -------------------------------------------------------------------
        // cleanup
        // -------------------------------------------------------------------
        sh """
            rm -fr artifacts
        """

        unarchive()

        sh """
            ls -la
        """
    }
}
